/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package geradorfigurinhas;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URL;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse.BodyHandlers;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

public class App {

    private static final String API_ADDRESS = "https://raw.githubusercontent.com/alura-cursos/imersao-java/api/TopMovies.json";

    public static void main(String[] args) throws IOException, InterruptedException {
        HttpClient client = HttpClient.newHttpClient();
        HttpRequest request = HttpRequest.newBuilder().uri(URI.create(API_ADDRESS)).build();
        String body = client.send(request, BodyHandlers.ofString()).body();
        
       JsonElement parsedBody = JsonParser.parseString(body);

       JsonObject jsonFullObject = parsedBody.getAsJsonObject();       
       JsonElement jsonItemElement = jsonFullObject.get("items");
       JsonArray jsonItemArray = jsonItemElement.getAsJsonArray();

       StickerGenerator stickerGenerator = new StickerGenerator();

       for(JsonElement item : jsonItemArray) {
           JsonObject jsonObject = item.getAsJsonObject();

           String titulo = jsonObject.get("title").getAsString();
           String urlImg = jsonObject.get("image").getAsString();
           
           //Retirando o caracter especial : do nome do arquivo pra evitar falha em escrever o arquivo em disco.
           String nomeDoArquivo = titulo.replace(":", "-")  + ".png";

           InputStream inputStream = new URL(urlImg).openStream();
           stickerGenerator.cria(inputStream, nomeDoArquivo, "TOPZERA");
       }
    }
}
